const authErrors = {
  EMAIL_NO_VALIDO: 'EMAIL_NO_VALIDO',
  EMAIL_YA_EN_USO: 'EMAIL_YA_EN_USO',
  CONTRASEÑA_DEMASIADO_CORTA: 'CONTRASEÑA_DEMASIADO_CORTA',
  CONTRASEÑA_NO_VALIDA: 'CONTRASEÑA_NO_VALIDA',
  NOMBRE_DE_USUARIO_YA_EN_USO: 'NOMBRE_DE_USUARIO_YA_EN_USO',
  NOMBRE_DE_USUARIO_NO_VALIDO: 'NOMBRE_DE_USUARIO_NO_VALIDO',
  EL_USUARIO_NO_EXISTE: 'EL_USUARIO_NO_EXISTE',
  ERROR_EN_EL_SERVIDOR_AL_AUTENTICAR_USUARIO: 'ERROR_EN_EL_SERVIDOR_AL_AUTENTICAR_USUARIO',
  PROVINCIA_NO_VALIDA: 'PROVINCIA_NO_VALIDA',
  CIUDAD_NO_VALIDA: 'CIUDAD_NO_VALIDA',
  DIRECCION_NO_VALIDA: 'DIRECCION_NO_VALIDA',
  CODIGO_POSTAL_NO_VALIDO: 'CODIGO_POSTAL_NO_VALIDO',
  NOMBRE_DE_USUARIO_DEMASIADO_CORTO: 'NOMBRE_DE_USUARIO_DEMASIADO_CORTO',
};

const jwtErrors = {
  ERROR_DEL_SERVIDOR_AL_GENERAR_EL_TOKEN: 'ERROR_DEL_SERVIDOR_AL_GENERAR_EL_TOKEN',
  EL_TOKEN_HA_EXPIRADO: 'EL_TOKEN_HA_EXPIRADO',
  CREDENCIALES_INVALIDAS: 'CREDENCIALES_INVALIDAS',
  ERROR_DESCONOCIDO_AL_VERIFICAR_EL_TOKEN: 'ERROR_DESCONOCIDO_AL_VERIFICAR_EL_TOKEN',
};

const bcryptErrors = {
  CREDENCIALES_INVALIDAS: 'CREDENCIALES_INVALIDAS',
  ERROR_EN_EL_SERVIDOR_AL_CHEQUEAR_CREDENCIALES: 'ERROR_EN_EL_SERVIDOR_AL_CHEQUEAR_CREDENCIALES',
};

const errorCodes = {
  authErrors,
  jwtErrors,
  bcryptErrors,
}

export default errorCodes;
