const errorCodes = {
  EMAIL_NOT_VALID: 'EMAIL_NOT_VALID',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  PASSWORD_INVALID_LENGTH: 'PASSWORD_INVALID_LENGTH',
  PASSWORD_NOT_VALID: 'PASSWORD_NOT_VALID',
  USERNAME_ALREADY_IN_USE: 'USERNAME_ALREADY_IN_USE',
  USERNAME_NOT_VALID: 'USERNAME_NOT_VALID',
  USER_NOT_EXISTS: 'USER_NOT_EXISTS',
};

export default errorCodes;
